all:
	@clear
	c++ *.cpp -Wall -Wextra -Werror -o megaphone
	./megaphone


# @clear: The @ symbol before the command suppresses the command output itself, 
# meaning the clear command will run, but clear won't be printed to the terminal. 
# The clear command clears the terminal screen.
